# Generated by Django 6.0.5 on 2026-05-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('hardness', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('location_found', models.TextField(help_text='Regions where this rock is common')),
                ('formation', models.TextField(help_text='The geological process that created this rock')),
                ('uses', models.TextField()),
                ('transparency', models.CharField(max_length=50)),
                ('fun_fact', models.TextField()),
            ],
        ),
    ]
