# Generated by Django 6.0.5 on 2026-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rock',
            old_name='hardness',
            new_name='hardness_max',
        ),
        migrations.AddField(
            model_name='rock',
            name='hardness_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
